# -*- coding: utf-8 -*-
"""basic_ops.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aWrAp5UYZaZZMkiDssyWYEGAgsyxkKv
"""

!pip install pandas
!pip install opencv-python numpy
!pip install matplotlib


import cv2
import numpy as np

# Đảm bảo ảnh nằm cùng thư mục
img = cv2.imread('opencv-logo.png')  

# Kiểm tra xem hình ảnh đã được tải chưa
if img is None:
    print("Không thể đọc hình ảnh. Vui lòng kiểm tra đường dẫn tệp.")
else:
    # 1. Truy cập và hiển thị giá trị pixel tại (100, 100)
    pixel = img[100, 100]
    print(f"Pixel tại (100, 100): {pixel}")  # Trả về [B, G, R]

    # 2. Truy cập từng kênh màu
    blue_value = img[100, 100, 0]
    print(f"Giá trị kênh Blue tại (100,100): {blue_value}")

    # 3. Thay đổi giá trị pixel tại (100, 100)
    img[100, 100] = [255, 255, 255]
    print(f"Pixel mới tại (100, 100): {img[100,100]}")

    # 4. Lấy thông tin ảnh
    print(f"Kích thước ảnh: {img.shape}")
    print(f"Số pixel: {img.size}")
    print(f"Kiểu dữ liệu ảnh: {img.dtype}")

    # 5. Cắt một phần ảnh (ROI)
    roi = img[280:340, 330:390]

    # 6. Dán ROI vào vị trí khác
    img[273:333, 100:160] = roi

    # 7. Tách các kênh màu
    b, g, r = cv2.split(img)

    # 8. Gộp lại các kênh
    merged = cv2.merge((b, g, r))

    # 9. Lưu ảnh kết quả
    cv2.imwrite('opencv_basic_ops_result.png', img)

    # Kết thúc
    print("Xử lý ảnh hoàn tất.")
