# -*- coding: utf-8 -*-
"""opencv_colorspaces.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyEkevy3DhpGHBGrgxQ4zf_4l0tobtFp
"""

pip install opencv-python

from google.colab.patches import cv2_imshow

# Bài tập chuyển đổi không gian màu trong OpenCV

import cv2
import numpy as np
# Import cv2_imshow from google.colab.patches for displaying images in Colab
from google.colab.patches import cv2_imshow


# Bước 1: Đọc ảnh gốc (ảnh đã có sẵn trong thư mục)
img = cv2.imread('opencv-logo.png')

# Kiểm tra nếu ảnh không tồn tại
if img is None:
    print("❌ Không thể đọc ảnh. Vui lòng kiểm tra lại tên file 'opencv-logo.png'.")
    exit()

# Bước 2: Chuyển đổi ảnh từ BGR sang Grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Lưu ảnh Grayscale
cv2.imwrite('opencv_colorspace_gray.png', gray)
print("[Bước 2] Đã chuyển đổi ảnh sang Grayscale và lưu thành 'opencv_colorspace_gray.png'.")

# Bước 3: Chuyển đổi ảnh từ BGR sang HSV
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# Lưu ảnh HSV
cv2.imwrite('opencv_colorspace_hsv.png', hsv)
print("[Bước 3] Đã chuyển đổi ảnh sang HSV và lưu thành 'opencv_colorspace_hsv.png'.")

# Bước 4: Hiển thị các kết quả ảnh
# Use cv2_imshow instead of cv2.imshow for displaying images in Colab
cv2_imshow(img)     # Hiển thị ảnh gốc
cv2_imshow(gray)   # Hiển thị ảnh Grayscale
cv2_imshow(hsv)          # Hiển thị ảnh HSV

# Chờ người dùng đóng cửa sổ ảnh
cv2.waitKey(0)
cv2.destroyAllWindows()

# Kết thúc
print("✅ Đã chuyển đổi ảnh sang các không gian màu và lưu kết quả.")

"""For example, here we download and display a PNG image of the Colab logo:"""